# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - resume-generation-system-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A873557C92BD44C68A65792E2AE3401D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2D74F9790FE4D3CAC61D582533D182B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B5245B90FF164AD9A07A0DD8D87A3BEA }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'resume-generation-system-backend'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/container/
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          acrName: dominion
          acrUsername: ${{ secrets.DOMINIONSERVER_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.DOMINIONSERVER_REGISTRY_PASSWORD }}
          containerAppName: rgs-container-funcs
          resourceGroup: ResumeGenerationSystem_group
          imageToBuild: dominion.azurecr.io/rgs-container-funcs:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
